CLASS ZTK_bp_bookingsupplement_u DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF ZTK_i_travel_u .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZTK_bp_bookingsupplement_u IMPLEMENTATION.
ENDCLASS.
