CLASS ZTKFK_bp_bookingsupplement_u DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF ZTKFK_i_travel_u .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZTKFK_bp_bookingsupplement_u IMPLEMENTATION.
ENDCLASS.
