"! @testing ZTKFK_CL_I_TRAVEL_TUM
"! @testing ZTKFK_CL_C_TRAVEL_TUM
"! @testing ZTKFK_CL_FLIGHT_LEGACY
"! @testing FUGR:ZTKFK_FLIGHT_TRAVEL_API
CLASS ltc DEFINITION FINAL INHERITING FROM ZTKFK_tc_flight_travel_api FOR TESTING RISK LEVEL HARMLESS DURATION MEDIUM.
ENDCLASS.
